### ISSUE TITLE
Integrating this with PowerTemplates

### ISSUE THREAD

**Issue by yuchi** [FokkeZB/css-layout-ti#1]
I’ve been working in the last months on an idea that I recently implemented, called PowerTemplates.

The idea is to be able to do the following:

``` xml
<ListView id="list" module="power-templates">
  <Templates>
    <ItemTemplate name="simple" itemId="[ id ]">
      <Label text="[ name ]" />
   </ItemTemplate>
  </Templates>
  <ListSection id="section"/>
</ListView>
```

``` js
$.section.items = [
  $.list.powerTemplates.simple.parse({ id: 12, name: 'Example' })
];
```

**Comment by yuchi** [comment]
I also implemented something very similar to your `Template.js` so you can create PowerTemplates outside of ListViews and build a view hierarchy out of them.

Just wanted to leave this here, so we can work together.

**Comment by FokkeZB** [comment]
Well, ultimately I'd like to see this layout system done on the native side, but doesn't hurt to link related efforts ;)

**Comment by yuchi** [comment]
I’ll push the template ➜ hierarchy very soon, but in the meanwhile here’s the package/module (titaniumified, of course)! https://github.com/smclab/power-templates

**Comment by yuchi** [comment]
Closing for obsolescence
